### ISSUE TITLE
Launcher tries to launch japanese version of koikatsu instead of steam version when both are installed

### ISSUE THREAD

**Issue by AdaBallard** [smokeofc/KoikatsuLaucher#1]
So if you put the laincher into Steam\steamapps\common\Koikatsu Party\ while having japanese version of the  game instaled  too, it will try to launch japanese one (and will show screenshots and cards folders from the japanese one too).

It.s necessary to check what exe is in the same folder with launcher, and if it's Koikatsu Party.exe, then launcher needs to use the path from HKEY_CURRENT_USER\Software\illusion\Koikatsu\Koikatsu Party\INSTALLDIR instead of HKEY_CURRENT_USER\Software\illusion\koikatu\koikatu\INSTALLDIR .

**Comment by smokeofc** [comment]
This is fixed in release 1.2.0
